### ISSUE TITLE
Gyro swapped

### ISSUE THREAD

**Issue by jlbp87** [Valkirie/HandheldCompanion#1338]
**Device manufacturer**
- [ ] AYANEO
- [ ] AYN
- [ ] AOKZOE
- [ ] ASUS
- [X] GPD
- [ ] LENOVO
- [ ] MSI
- [ ] ONEXPLAYER
- [ ] VALVE

**Device model**
GPD Win Max 2
**Handheld Companion Version**
0.28.2.2
**Describe the bug**
The Gyro function of the x and y is swapped in Handheld Companion.
When I turn the device left or right, the joystick or mouse cursor moves up and down.
When I tilt the device up or down, the joystick or mouse cursor moves left and right.
No problem with Motion Assistant.

**Comment by jlbp87** [comment]
Perhaps an option to swap "x" and "y", if possible, would solve the problem. Great work with this utility!

**Comment by Valkirie** [comment]
Issue should be fixed on latest early access release, available on patreon.

**Comment by jlbp87** [comment]
I'm testing Build 0.28.3.1, and unfortunately, the problem persists on my Win Max 2 HX370 :(
Regards.

**Comment by Soullessgod3** [comment]
its happening still to me as well AI 9 HX 370 gpd win 4 ... im just gonna uninstall
