### ISSUE TITLE
Applying a Desktop layout to a profile doesn't choose the current Desktop profile, but the original one

### ISSUE THREAD

**Issue by Havner** [Valkirie/HandheldCompanion#443]
Tested on [8eb8216](https://github.com/Valkirie/HandheldCompanion/commit/8eb82164778171007503b8aca2af358b760e64cb)
AFAIR it's a regression on 0.15.0.4, but that version had its own issues with linking those profile.

Like in the title. The layout you end up with is not your current Desktop profile, but the original profile that is there when you start the HC for the first time ever, e.g. the default Desktop profile.

**Comment by Havner** [comment]
It's even more complicated.

I've created a new profile for a game A. Applied desktop template to it, it applied the original Desktop, not the current one. I've edited a profile for the game A.
Then I created a new profile for the game B. Applied desktop template to it and it applied the layout for game A :-)

**Comment by Havner** [comment]
Another strange thing happened. The controls that got inherited for the game B from game A don't work. They show in the UI, but don't work in the game (those particular ones were keyboard bindings on d-pad). Restarted the HC, they were still in the UI, but didn't work in game. I've reassigned them (selected None, they Keyboard again and found a key) and they started to work.

There is some UI <-> backend inconsistency here.

**Comment by Valkirie** [comment]
> It's even more complicated.
> 
> I've created a new profile for a game A. Applied desktop template to it, it applied the original Desktop, not the current one. I've edited a profile for the game A. Then I created a new profile for the game B. Applied desktop template to it and it applied the layout for game A :-)

I can reproduce this.

**Comment by Valkirie** [comment]
I guess I fixed all the above : https://github.com/Valkirie/HandheldCompanion/commit/46c90032175e438a54791f3b42c292a489602fc4

**Comment by Havner** [comment]
> I guess I fixed all the above : [46c9003](https://github.com/Valkirie/HandheldCompanion/commit/46c90032175e438a54791f3b42c292a489602fc4)

Thanks, I'll test today/tomorrow

**Comment by Havner** [comment]
Not fixed. Still when you apply the Desktop profile to some another profile you end up with the original/default Desktop profile. Not your current one.

**Comment by Valkirie** [comment]
Oh yes. To be fair that's not a bug. I voluntarily splitters both.

**Comment by Havner** [comment]
So how can I apply my current one? Can I at all? It sits in the layout directory and is getting updated when modified. So by assumption it should be that one.

If that is intentional, yeah, it should be somehow named differently or maybe your current desktop one should be saved in some other directory? Not in layouts.

**Comment by Havner** [comment]
On some rethinking, when we have community templates and ability to export our profiles as templates in the future having the Desktop template hardcoded (like you did) actually makes sense. This can be useful when someone breaks its own Desktop to return it to defaults.

What I would suggest though is to move the saved Desktop file from layouts directory to some other place (e.g. where HC settings are stored) not to confuse this file with the other templates as it is not one of them. This is the reason I got confused in the first place.
